config/routes.rb
StackGardenhose::Application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resources :questions, only: [:index, :new, :create, :show, :edit, :update] do
    resources :answers, only: [:new, :create, :edit, :update]
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :votes, only: [:new, :create]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :user, :question
  belongs_to :user
  belongs_to :question

  has_many :votes, :as => :votable
  validates :body, :user, :question, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :user_id
  belongs_to :user
  has_many :answers
  has_many :votes, :as => :votable
  validates :title, :body, :user, presence: true


  def can_answer?(user)
    !owner? user
  end

  def owner?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password
  has_secure_password
  has_many :questions
  has_many :answers
  validates :email, :uniqueness => true
  validates :name, :email, :presence => true

  def can_answer?(question)
    question.can_answer?(self)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :value, :user, :votable_id, :votable_type, :user_id
  belongs_to :votable, polymorphic: true
  belongs_to :user
  validates :user_id, uniqueness: { scope: [:votable_id, :votable_type] }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  #REVIEW: you're not using this action, remove it.
  def new
  end

  def create
    @answer = Answer.new(params[:answer])
    @answer.user = current_user
    @answer.save

    if @answer.save
      redirect_to question_path(@answer.question)
    else
      flash[:error] = @answer.errors
      redirect_to question_path(@answer.question)
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
    if current_user.id == @answer.user_id
      render :edit
    else
      flash[:message] = "Must be author of answer to edit"
      redirect_to question_path(@question, @answer)
    end

  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update_attributes(params[:answer])
    redirect_to question_path(@answer.question)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Authentication #see lib

  helper_method :current_user  #only exposes this method to views
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # REVIEW: you've already included these modules in the application controller, remove them from here.
  include ApplicationHelper
  include QuestionHelper
  before_filter :redirect_to_signup, :only => [:new]
  before_filter :authorize_user, :only => [:create, :edit, :update]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    if @question.save
      redirect_to root_path
    else
      # flash[:error] = @question.errors
      render :new
    end
  end

  def show
    @vote = Vote.new
    @question = Question.find params[:id]
  end

  def edit
    @question = Question.find params[:id]
  end

  def update
    @question = Question.find params[:id]
    @question.update_attributes(params[:question])
    redirect_to @question
  end

  private
  def authorize_user
    redirect_to @question, :notice => "Sorry, only the creator can edit a question" unless @question.owner?(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_path(user)
    else
      #create an error message and have them try signing in again
      render :new
    end

  end

  def destroy
    session.clear
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login @user
      redirect_to @user
    else
      flash.now[:error] = "Invalid signup"
      # puts @user.errors
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    votable = params[:votable_type].classify.constantize.find params[:votable_id]
    votable.votes.create params[:vote]
    render :json => render_to_string(:partial => 'votes/counter', :locals => { votable: votable} ).to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_image_source
    email = current_user.email
    hash = Digest::MD5.hexdigest(email)
    "http://www.gravatar.com/avatar/#{hash}"
  end
end

app/helpers/question_helper.rb
module QuestionHelper



end

app/helpers/votes_helper.rb
module VotesHelper
  def upvote_form vote
    vote_form 1
  end

  def downvote_form vote
    vote_form -1
  end

  def vote_form value
    # write your erb
  end
end

app/views/answers/_errors.html.erb
<% if flash[:error] %>
  <div id="errorExplanation">
  <h2><%= pluralize(flash[:error].count, "error") %>
    prohibited this answer from being saved:</h2>
    <ul>
      <% flash[:error].full_messages.each do |msg| %>
        <li><%= msg %></li><br />
      <% end %>
    </ul>
  </div>
<% end %>

<% if object.errors.any? %>
  <% object.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

app/views/answers/_new.html.erb
<h3>Submit an answer</h3>

<%= form_for [question, answer] do |f| %>
  <%= f.label "What do you think?" %><br />
  <%= hidden_field_tag("answer[question_id]", question.id) %>
  <%= f.text_area :body %><br />
  <%= f.submit "Answer it!" %>
<% end %>
  <%= render partial: 'errors' %>

app/views/answers/_show.html.erb
<li><%= answer.body %> | <%= render partial: "votes/form", locals: {votable: answer } %>

    <% if current_user.id == answer.user_id %>
      <%= link_to "Edit Your Answer", edit_question_answer_path(@question, answer) %>
    <%end %>

</li>

app/views/answers/edit.html.erb
<%= form_for [@question, @answer] do |f| %>
  <%= f.label "What do you think?" %><br />
  <%= f.text_area :body, :placeholder => @answer.body %><br />
  <%= f.submit "Yeah, this is a way better answer. Send it!" %>
<% end %>
  <%= render partial: 'errors' %>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <%= link_to "All Questions", root_path %>
  <% if current_user %>
    <%= link_to "Your Profile", current_user %>
    <%= link_to "Logout", signout_path, method: 'delete' %>
  <% else %>
    <%= link_to "Sign In", signin_path %>
    <%= link_to "Sign Up", signup_path%>
  <% end %>
</div>


  
    
  
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackGardenhose</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>

<%= yield %>

</body>
</html>

app/views/questions/_errors.html.erb
<% if flash[:error] %>
  <div id="errorExplanation">
  <h2><%= pluralize(flash[:error].count, "error") %>
    prohibited this question from being saved:</h2>
    <ul>
      <% flash[:error].full_messages.each do |msg| %>
        <li><%= msg %></li><br />
      <% end %>
    </ul>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%= form_for @question, url: {action: "update"} do |f| %>
<%= f.label "Title:" %>
<%= f.text_field :title, :placeholder => @question.title %><br />
<%= f.label "Your question:" %><br />
<%= f.text_area :body, :placeholder => @question.body %><br />
<%= f.submit "Update your question" %>
<% end %>

app/views/questions/index.html.erb
<h1>Below are all the questions!</h1>

<ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to "#{question.title}", question_path(question) %> | <%= render partial: "votes/counter", locals: {votable: question} %> 
    </li>
  <% end %>
</ul>

<%= link_to "Ask a question", new_question_path %>

app/views/questions/new.html.erb
<h1>Submit a Question</h1>

<%= form_for @question do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %><br>
  <%= f.errors[:title] %>
  <%= f.label "Content" %><br>
  <%= f.text_area :body %><br>
  <%= f.submit "Create Question" %>
<% end %>

<%= render partial: 'errors', :object => @question %>

<%= link_to "Back to Home!", questions_path %>

app/views/questions/show.html.erb
<h1>Below is the selected question</h1>
<div class="error-render">
  <% if flash[:message] %>
    <%= flash[:message] %>
  <% end %>
</div>
<h3><%= @question.title %></h3>

<%= render partial: 'votes/form', locals: { votable: @question } %>

<h4><%= @question.body %></h4>

<% if @question.answers.any? %>
<ul>
  <% @question.answers.each do |answer| %>
    <%= render partial: 'answers/show', locals: { answer: answer } %>
  <% end %>
</ul>
<% end %>

<% if current_user && current_user.can_answer?(@question) %>
  <%= render 'answers/new', question: @question, answer: @question.answers.build %>
<% else %>
  <%= link_to "Edit your question", edit_question_path(@question) %>
<% end%>

app/views/users/new.html.erb
<h2> Create an Account </h2>

<%= form_for @user do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <br />
  <%= f.label "Password" %>
  <%= f.text_field :password %>
  <br>
  <%= f.submit "Sign Up!" %>
<%end%>

<% if flash[:error] %>
   <div><%= flash[:error] %></div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.name %></h1>
<img src="<%=gravatar_image_source%>">

<h2>Questions you've asked.</h2>

<ul>
  <% current_user.questions.each do |question| %>
    <li>
      <%= link_to "#{question.title}", question %> | <%= render partial: "votes/counter", locals: {votable: question} %>
    </li>
  <% end %>
</ul>


<h2>Answers you've given.</h2>

<ul>
  <% current_user.answers.each do |answer| %>
  <li>
    <%= link_to "#{answer.question.title}", answer.question %> | <%= render partial: "votes/counter", locals: {votable: answer.question} %>
    <ul>
      <li>
        <%= answer.body %> | <%= render partial: "votes/counter", locals: {votable: answer} %>
      </li>
    </ul>
  </li>
  <% end %>
</ul>

app/views/votes/_counter.html.erb
<strong>Karma: </strong><%= votable.votes.where(value: 1).count - votable.votes.where(value: -1).count %>

app/views/votes/_form.html.erb
<div id="votes_form_container">

<span>
  <%= render "votes/counter", votable: votable %>
</span>

<% if current_user %>

  REVIEW: use helpers, create a helper upvote_form, donwvote_form both these methods should use a vote_form(value)
  <%= upvote_form %>
  <%= form_for @vote, remote: true do |f| %>
    <%= f.hidden_field :value, :value => 1 %>
    <%= f.hidden_field :votable_id, :value => votable.id %>
    <%= f.hidden_field :votable_type, :value => votable.class %>
    <%= f.submit "Upvote" %>
  <% end %>

  <%= form_for @vote, remote: true do |f| %>
    <%= f.hidden_field :value, :value => -1 %>
    <%= f.hidden_field :votable_id, :value => votable.id %>
    <%= f.hidden_field :votable_type, :value => votable.class %>
    <%= f.submit "Downvote" %>
  <% end %>

<% end %>

</div>